### ISSUE TITLE
try_lock_order() is unsafe

### ISSUE THREAD

**Issue by CSCPF2** [seanmonstar/try-lock#1]
Locking with anything less than `(Acquire, Release)` by default is unsafe because `Relaxed` ordering does not have ordering guarantee on the protected value.

The following function needs to be made `unsafe` (or private):
https://github.com/seanmonstar/try-lock/blob/90a682467dfbaf762a8986d406c6af6851af2ebd/src/lib.rs#L91-L107

**Comment by seanmonstar** [comment]
Good point, I had originally meant it to allow making the ordering stricter, and didn't think of someone making it looser.

**Comment by seanmonstar** [comment]
Thanks for helping fix this, I've published v0.2.3.
