### ISSUE TITLE
Add a release pub fn

### ISSUE THREAD

**Issue by beckend** [seanmonstar/try-lock#10]
Using this struct `Locked` on a custom Guard, upon drop, I need to release the lock before I can signal the rest of the app.

**Comment by seanmonstar** [comment]
The lock is released when you drop the guard.

**Comment by beckend** [comment]
It's released after the drop, I cannot signal when something is already dropped.

**Comment by beckend** [comment]
Consider this precise usecase:
https://github.com/smol-rs/event-listener/blob/c7757f5eced6c90cffacd64bf53c65a08a5d9f82/examples/mutex.rs

**Comment by beckend** [comment]
The queue can never continue because it's on the drop we could signal the queue to go on.

**Comment by seanmonstar** [comment]
Most lock guards in Rust work this way. To add what you're asking, it'd look like this:

```rust
pub fn release(self) {
    drop(self)
}
```

**Comment by beckend** [comment]
do you mean like this:

```rust
pub fn release(self) {
    drop(self);
    // it's already dropped and cannot work
    self.1.lock_ops.notify(1);
}
```

**Comment by beckend** [comment]
I am asking for:

```rust
pub fn release(self) {
   self.0.data.release();
   self.1.lock_ops.notify(1);
   drop(self);
}
```

**Comment by seanmonstar** [comment]
Rust lock guards (in this crate, in libstd, elsewhere) all work based on `Drop`.

If you're trying to control a specific set of things in your own `Drop`, you can do so by. Try putting the guard in an `Option`, and then `self.guard = None` will drop the guard.

This is not something that this library needs to solve.
