### ISSUE TITLE
Lock ordering in default `try_lock` is not strong enough

### ISSUE THREAD

**Issue by oribs1** [seanmonstar/try-lock#6]
When you are "locking" the Lock, you use `swap` on the `AtomicBool`. `swap` is both reading and writing to the AtomicBool, and therefore in order to be safe need to have both Acquire And Release Order, so AcqRel or SeqCst. You can see it is being mentioned here: https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html#method.swap

With this implementation, I think you can get into a situation where two different threads get into the Lock

**Comment by yvt** [comment]
No, it's already strong enough. Note the following description about [the C++ memory orderings](https://en.cppreference.com/w/cpp/atomic/memory_order):

> `std::memory_order` specifies how memory accesses, including regular, non-atomic memory accesses, are to be ordered **around an atomic operation**.

> **All modifications to any particular atomic variable occur in a total order** that is specific to this one atomic variable.

(emphases mine)

Using `AcqRel` on a lock operation (`locked ← true`) allows another thread observing `locked == true` to synchronize subsequent regular memory accesses to the contents with the first lock operation. However, observing `locked == true` means lock failure, so there are no such subsequent memory accesses.
